import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ["image/avif", "image/webp"],
  },

  // 301 redirects preserving Google rankings from the old site during the domain
  // migration. Source: colourfulindianholidays.com GSC export (last 3 months,
  // 222 clicks / 40,632 impressions / 124 ranked pages) captured pre-launch.
  // Every mapped page keeps its existing search equity instead of 404ing.
  //
  // Status categories (see /home/claude/redirect_map_v2.csv for the full audit):
  //  - renamed-slug:        exact new-site page exists at a different URL
  //  - regional-fallback:   no direct new-site equivalent; sent to the closest region
  //  - package-category-fallback: old individual /tour/xxx page -> its new category hub
  //  - travel-guide-article / festival-new-page / beaches-new-page / wildlife-new-page:
  //        pages that need to be BUILT at the new URL (see conversation) — until then
  //        these redirects point at the nearest live page so nothing 404s meanwhile
  async redirects() {
    return [
      // Active backlink campaign (Jun–Aug 2026) — verified against
      // Backlink-August-26 tracking sheet, ~50 live backlinks point here.
      { source: "/kashmir-holiday-tour-package", destination: "/packages/kashmir-ladakh-tours", permanent: true },
      { source: "/india-nepal-bhutan-tour-packages", destination: "/packages/india-nepal-bhutan-tours", permanent: true },
      { source: "/nepal-bhutan-tour-packages", destination: "/packages/nepal-bhutan-tours", permanent: true },
      { source: "/rajasthan-heritage-tour-package", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/north-india-travel-packages", destination: "/packages/north-india-tours", permanent: true },
      { source: "/cultural-golden-triangle-with-varanasi-tour-packages", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour-operators-in-jaipur-rajasthan", destination: "/destinations/rajasthan", permanent: true },
      { source: "/destinations/ranthambore", destination: "/destinations/rajasthan/ranthambore", permanent: true },
      { source: "/pilgrimage-holiday-destinations-in-india", destination: "/travel-guide/pilgrimage-holiday-destinations-in-india", permanent: true },
      { source: "/monuments-in-rajasthan", destination: "/travel-guide/monuments-in-rajasthan", permanent: true },
      { source: "/destinations/haridwar-rishikesh", destination: "/destinations/rishikesh-haridwar", permanent: true },
      { source: "/luxury-beaches/tamil-nadu-beaches", destination: "/destinations/tamil-nadu-beaches", permanent: true },
      { source: "/20-best-tourist-places-to-visit-in-india", destination: "/travel-guide/20-best-tourist-places-to-visit-in-india", permanent: true },
      { source: "/places-to-visit-in-shekhawati", destination: "/travel-guide/places-to-visit-in-shekhawati", permanent: true },
      { source: "/tour/cultural-golden-triangle-with-historical-rajasthan", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/fair-festivals/kumbh-mela", destination: "/themes/festival-tours/kumbh-mela", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/tour", destination: "/packages", permanent: true },
      { source: "/tour/14-days-rajasthan-tour-itinerary", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/india-golden-triangle-tour", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/fair-festivals/the-urs-festival-ajmer", destination: "/themes/festival-tours/the-urs-festival-ajmer", permanent: true },
      { source: "/6-day-golden-triangle-tour-india", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/south-india-tamilnadu-kerala-tour", destination: "/packages/kerala-tours", permanent: true },
      { source: "/destinations/bikaner", destination: "/destinations/rajasthan/bikaner", permanent: true },
      { source: "/fair-festivals/elephant-festival", destination: "/themes/festival-tours/elephant-festival", permanent: true },
      { source: "/luxury-beaches/gujarat-beaches", destination: "/destinations/gujarat-beaches", permanent: true },
      { source: "/fair-festivals/teej-festival", destination: "/themes/festival-tours/teej-festival", permanent: true },
      { source: "/taj-mahal-tour-packages", destination: "/packages/taj-mahal-tours", permanent: true },
      { source: "/luxury-beaches", destination: "/destinations", permanent: true },
      { source: "/north-india-tours", destination: "/packages/north-india-tours", permanent: true },
      { source: "/north-india-nepal-tours", destination: "/packages/north-india-tours", permanent: true },
      { source: "/tour/golden-triangle-with-ranthambore-kerala", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/14-days-cultural-golden-triangle-with-rajasthan", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/wildlife-attractions/sariska-wildlife-sanctuary", destination: "/destinations/sariska", permanent: true },
      { source: "/fair-festivals/camel-festival", destination: "/themes/festival-tours/camel-festival", permanent: true },
      { source: "/taj-mahal-tour-from-delhi-by-car", destination: "/packages/taj-mahal-tours", permanent: true },
      { source: "/top-cultural-festivals-in-india", destination: "/travel-guide/top-cultural-festivals-in-india", permanent: true },
      { source: "/destinations/mount-abu", destination: "/destinations/rajasthan/mount-abu", permanent: true },
      { source: "/destinations/kochi", destination: "/destinations/kerala", permanent: true },
      { source: "/destinations/gangtok", destination: "/destinations", permanent: true },
      { source: "/fair-festivals", destination: "/themes/festival-tours", permanent: true },
      { source: "/destinations/aurangabad", destination: "/destinations", permanent: true },
      { source: "/tours", destination: "/travel-guide", permanent: true },
      { source: "/fair-festivals/diwali", destination: "/themes/festival-tours/diwali", permanent: true },
      { source: "/fair-festivals/goa-carnival", destination: "/themes/festival-tours/goa-carnival", permanent: true },
      { source: "/rajasthan-tour-packages", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/wildlife-attractions/bandhavgarh-national-park", destination: "/destinations/bandhavgarh", permanent: true },
      { source: "/taj-mahal-tour-from-delhi", destination: "/packages/taj-mahal-tours", permanent: true },
      { source: "/tour/delhi-agra-same-day-by-super-fast-train", destination: "/packages", permanent: true },
      { source: "/fair-festivals/onam", destination: "/themes/festival-tours/onam", permanent: true },
      { source: "/blog", destination: "/travel-guide", permanent: true },
      { source: "/top-10-splendors-of-vivid-rajasthan", destination: "/travel-guide/top-10-splendors-of-vivid-rajasthan", permanent: true },
      { source: "/tour/10-days-golden-triangle-with-colourful-rajasthan-tour", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/luxury-beaches/andaman-nicobar-beaches", destination: "/destinations/andaman-nicobar-beaches", permanent: true },
      { source: "/tour/10-days-golden-triangle-with-historical-rajasthan-tour", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/fair-festivals/international-yoga-festival-rishikesh", destination: "/themes/festival-tours/international-yoga-festival-rishikesh", permanent: true },
      { source: "/tour/golden-triangle-tour-with-nepal", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/rajasthan-forts-palaces-tour", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/destinations/sarnath", destination: "/destinations/varanasi", permanent: true },
      { source: "/tour/cultural-golden-triangle-with-bengal-tiger", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/wildlife-attractions", destination: "/destinations", permanent: true },
      { source: "/5-day-kerala-tour-plan", destination: "/packages/kerala-tours", permanent: true },
      { source: "/e-tourist-visa", destination: "/travel-guide/e-tourist-visa", permanent: true },
      { source: "/fair-festivals/pushkar-fair", destination: "/themes/festival-tours/pushkar-fair", permanent: true },
      { source: "/south-india-tours", destination: "/packages/south-india-tours", permanent: true },
      { source: "/tour/6-days-amazing-kerala-tour", destination: "/packages/kerala-tours", permanent: true },
      { source: "/luxury-beaches/maharashtra-beaches", destination: "/destinations/maharashtra-beaches", permanent: true },
      { source: "/wildlife-attractions/kaziranga-national-park", destination: "/destinations/kaziranga", permanent: true },
      { source: "/tour/golden-triangle-with-mandawa-and-ranthambore-tiger-safari", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/wildlife-tours", destination: "/packages/wildlife-tours", permanent: true },
      { source: "/tour/priceless-gems-of-royal-rajasthan-tour", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/top-monsoon-destinations", destination: "/travel-guide/top-monsoon-destinations", permanent: true },
      { source: "/tour/central-india-with-rajasthan", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/destinations/jaisalmer", destination: "/destinations/rajasthan/jaisalmer", permanent: true },
      { source: "/tour/rajasthan-with-goa-tour", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/tour/grand-golden-triangle-with-blissful-bird-watching", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/destinations/orchha", destination: "/destinations/rajasthan", permanent: true },
      { source: "/famous-temples-to-visit-in-rajasthan", destination: "/travel-guide/famous-temples-to-visit-in-rajasthan", permanent: true },
      { source: "/destinations/surat", destination: "/destinations", permanent: true },
      { source: "/kashmir-leh-tours", destination: "/packages/kashmir-ladakh-tours", permanent: true },
      { source: "/destinations/mathura", destination: "/destinations/agra", permanent: true },
      { source: "/tour/golden-triangle-with-haridwar-rajasthan-tour", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/india-tiger-tour", destination: "/packages/wildlife-tours", permanent: true },
      { source: "/destinations/dalhousie", destination: "/destinations/himachal", permanent: true },
      { source: "/destinations/jaipur", destination: "/destinations/rajasthan/jaipur", permanent: true },
      { source: "/category/blog", destination: "/travel-guide", permanent: true },
      { source: "/tour/north-india-with-nepal-and-bhutan-tour", destination: "/packages/north-india-tours", permanent: true },
      { source: "/destinations/dharamshala", destination: "/destinations/himachal", permanent: true },
      { source: "/destinations/shimla", destination: "/destinations/himachal", permanent: true },
      { source: "/safari-trip-to-corbett-national-park", destination: "/travel-guide", permanent: true },
      { source: "/destinations/bharatpur", destination: "/destinations/rajasthan", permanent: true },
      { source: "/tour/golden-triangle-with-ranthmbhore", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/south-india-tour", destination: "/packages/south-india-tours", permanent: true },
      { source: "/tour/best-of-india-nepal-first-tour", destination: "/packages/nepal-tours", permanent: true },
      { source: "/tour/07-days-kashmir-tour", destination: "/packages/kashmir-ladakh-tours", permanent: true },
      { source: "/tour/golden-triangle-with-pushkar", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/north-india-tour", destination: "/packages/north-india-tours", permanent: true },
      { source: "/destinations/manali", destination: "/destinations/himachal", permanent: true },
      { source: "/india-golden-triangle-private-tour-packages", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/golden-triangle-with-gods-own-country-kerala", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tag/rajasthan", destination: "/travel-guide", permanent: true },
      { source: "/tour/rajasthan-with-varanasi-tour", destination: "/packages/rajasthan-tours", permanent: true },
      { source: "/tour/indian-wildlife-tour", destination: "/packages/wildlife-tours", permanent: true },
      { source: "/tour/10-days-himalayan-journey", destination: "/packages", permanent: true },
      { source: "/india-golden-triangle-private-tour", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/9-days-with-birds-of-yamuna-and-chambal-and-bengal-tiger", destination: "/packages/wildlife-tours", permanent: true },
      { source: "/fair-festivals/kutch-mahotsav", destination: "/themes/festival-tours/kutch-mahotsav", permanent: true },
      { source: "/tour/05-days-kashmir", destination: "/packages/kashmir-ladakh-tours", permanent: true },
      { source: "/tour/rajasthan-with-wildlife-tour", destination: "/packages/wildlife-tours", permanent: true },
      { source: "/tour/north-india-with-orchha-tour", destination: "/packages/north-india-tours", permanent: true },
      { source: "/tour/06-days-magical-himalaya", destination: "/packages", permanent: true },
      { source: "/tour/09-days-kashmir-tour", destination: "/packages/kashmir-ladakh-tours", permanent: true },
      { source: "/tour/north-east-tour-2", destination: "/packages", permanent: true },
      { source: "/tour/jaipur-agra-same-day-train-tour", destination: "/packages", permanent: true },
      { source: "/tour/wildlife-golden-triangle-tour-of-india", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/7-days-golden-triangle-with-mumbai", destination: "/packages/golden-triangle-tours", permanent: true },
      { source: "/tour/kerala-in-10-days", destination: "/packages/kerala-tours", permanent: true },
      { source: "/tour/paradise-of-hills-valley", destination: "/packages", permanent: true },
      { source: "/tour/best-of-india-nepal-third-tour", destination: "/packages/nepal-tours", permanent: true },
    ];
  },
};

export default nextConfig;
