import type { MetadataRoute } from "next";
import { execSync } from "node:child_process";
import path from "node:path";
import { SITE_URL } from "@/lib/seo/business";

// Fixed fallback date — used only when a real per-file date can't be
// determined (see getLastModified below). A sitemap that reports every
// URL as "modified today, on every deploy" carries no real freshness
// signal and can train Google to stop trusting lastmod entirely (see
// FULLAUDITREPORT.md finding T3), which is exactly the failure mode a
// single shared "today" constant would reproduce. Bump this only if the
// git-based lookup below is ever unavailable for an extended period.
const FALLBACK_LAST_UPDATED = new Date("2026-09-30");

// Real per-page lastmod, sourced from each page's own git history rather
// than one shared constant or a fabricated per-page value (see
// ACTION-PLAN.md #29). Every route in this file maps directly onto a
// `src/app<path>/page.tsx` source file, so the file's own last commit
// date is exactly the page's real last-edit date — no guessing involved.
//
// This depends on the build having real git history available (true for
// a standard Vercel deploy, which clones the repo). If git isn't
// available, or a file's history can't be resolved for any reason, this
// falls back to FALLBACK_LAST_UPDATED rather than failing the build or
// reporting a wrong date.
function getLastModified(urlPath: string): Date {
  const filePath = path.join("src/app", urlPath, "page.tsx");
  try {
    const iso = execSync(`git log -1 --format=%cI -- "${filePath}"`, {
      cwd: process.cwd(),
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (!iso) return FALLBACK_LAST_UPDATED;
    const date = new Date(iso);
    if (Number.isNaN(date.getTime())) return FALLBACK_LAST_UPDATED;
    return date;
  } catch {
    return FALLBACK_LAST_UPDATED;
  }
}

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: SITE_URL,
      lastModified: getLastModified(""),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${SITE_URL}/destinations`,
      lastModified: getLastModified("/destinations"),
      changeFrequency: "weekly",
      priority: 0.95,
    },
    {
      url: `${SITE_URL}/destinations/nepal`,
      lastModified: getLastModified("/destinations/nepal"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/destinations/bhutan`,
      lastModified: getLastModified("/destinations/bhutan"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/destinations/rajasthan`,
      lastModified: getLastModified("/destinations/rajasthan"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/destinations/jaipur`,
      lastModified: getLastModified("/destinations/jaipur"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/destinations/udaipur`,
      lastModified: getLastModified("/destinations/udaipur"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/destinations/jodhpur`,
      lastModified: getLastModified("/destinations/jodhpur"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/destinations/jaisalmer`,
      lastModified: getLastModified("/destinations/jaisalmer"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/destinations/pushkar`,
      lastModified: getLastModified("/destinations/pushkar"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/destinations/delhi`,
      lastModified: getLastModified("/destinations/delhi"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/destinations/agra`,
      lastModified: getLastModified("/destinations/agra"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/destinations/varanasi`,
      lastModified: getLastModified("/destinations/varanasi"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/destinations/ranthambore`,
      lastModified: getLastModified("/destinations/ranthambore"),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/destinations/tamil-nadu-beaches`,
      lastModified: getLastModified("/destinations/tamil-nadu-beaches"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/gujarat-beaches`,
      lastModified: getLastModified("/destinations/gujarat-beaches"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/maharashtra-beaches`,
      lastModified: getLastModified("/destinations/maharashtra-beaches"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/andaman-islands`,
      lastModified: getLastModified("/destinations/andaman-islands"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/leh-ladakh`,
      lastModified: getLastModified("/destinations/leh-ladakh"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/srinagar-kashmir`,
      lastModified: getLastModified("/destinations/srinagar-kashmir"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/himachal`,
      lastModified: getLastModified("/destinations/himachal"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/rishikesh-haridwar`,
      lastModified: getLastModified("/destinations/rishikesh-haridwar"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/darjeeling`,
      lastModified: getLastModified("/destinations/darjeeling"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/goa`,
      lastModified: getLastModified("/destinations/goa"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/mumbai`,
      lastModified: getLastModified("/destinations/mumbai"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/kerala`,
      lastModified: getLastModified("/destinations/kerala"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/madurai`,
      lastModified: getLastModified("/destinations/madurai"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/chennai`,
      lastModified: getLastModified("/destinations/chennai"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/amritsar`,
      lastModified: getLastModified("/destinations/amritsar"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/mahabalipuram`,
      lastModified: getLastModified("/destinations/mahabalipuram"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/pondicherry`,
      lastModified: getLastModified("/destinations/pondicherry"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/khajuraho`,
      lastModified: getLastModified("/destinations/khajuraho"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/kanha`,
      lastModified: getLastModified("/destinations/kanha"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/pench`,
      lastModified: getLastModified("/destinations/pench"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/sikkim`,
      lastModified: getLastModified("/destinations/sikkim"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/kolkata`,
      lastModified: getLastModified("/destinations/kolkata"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/odisha`,
      lastModified: getLastModified("/destinations/odisha"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/gujarat`,
      lastModified: getLastModified("/destinations/gujarat"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/maharashtra`,
      lastModified: getLastModified("/destinations/maharashtra"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/sariska`,
      lastModified: getLastModified("/destinations/sariska"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/bandhavgarh`,
      lastModified: getLastModified("/destinations/bandhavgarh"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/kaziranga`,
      lastModified: getLastModified("/destinations/kaziranga"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/kathmandu`,
      lastModified: getLastModified("/destinations/kathmandu"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/pokhara`,
      lastModified: getLastModified("/destinations/pokhara"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/chitwan`,
      lastModified: getLastModified("/destinations/chitwan"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/nagarkot`,
      lastModified: getLastModified("/destinations/nagarkot"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/lumbini`,
      lastModified: getLastModified("/destinations/lumbini"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/everest-region`,
      lastModified: getLastModified("/destinations/everest-region"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/thimphu`,
      lastModified: getLastModified("/destinations/thimphu"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/paro`,
      lastModified: getLastModified("/destinations/paro"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/punakha`,
      lastModified: getLastModified("/destinations/punakha"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/destinations/gangtey`,
      lastModified: getLastModified("/destinations/gangtey"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/contact`,
      lastModified: getLastModified("/contact"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide`,
      lastModified: getLastModified("/travel-guide"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide/pilgrimage-holiday-destinations-in-india`,
      lastModified: getLastModified("/travel-guide/pilgrimage-holiday-destinations-in-india"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/top-cultural-festivals-in-india`,
      lastModified: getLastModified("/travel-guide/top-cultural-festivals-in-india"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/places-to-visit-in-shekhawati`,
      lastModified: getLastModified("/travel-guide/places-to-visit-in-shekhawati"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/monuments-in-rajasthan`,
      lastModified: getLastModified("/travel-guide/monuments-in-rajasthan"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/golden-triangle-itinerary-guide`,
      lastModified: getLastModified("/travel-guide/golden-triangle-itinerary-guide"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide/taj-mahal-visiting-guide`,
      lastModified: getLastModified("/travel-guide/taj-mahal-visiting-guide"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide/rajasthan-itinerary-guide`,
      lastModified: getLastModified("/travel-guide/rajasthan-itinerary-guide"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide/first-trip-to-india-guide`,
      lastModified: getLastModified("/travel-guide/first-trip-to-india-guide"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/travel-guide/solo-travel-india-guide`,
      lastModified: getLastModified("/travel-guide/solo-travel-india-guide"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/india-currency-payments-guide`,
      lastModified: getLastModified("/travel-guide/india-currency-payments-guide"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/india-health-vaccination-guide`,
      lastModified: getLastModified("/travel-guide/india-health-vaccination-guide"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/travel-guide/getting-around-india`,
      lastModified: getLastModified("/travel-guide/getting-around-india"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/travel-guide/india-e-visa-guide`,
      lastModified: getLastModified("/travel-guide/india-e-visa-guide"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/travel-guide/hiring-a-car-in-rajasthan`,
      lastModified: getLastModified("/travel-guide/hiring-a-car-in-rajasthan"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/travel-guide/20-best-tourist-places-to-visit-in-india`,
      lastModified: getLastModified("/travel-guide/20-best-tourist-places-to-visit-in-india"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/about-us`,
      lastModified: getLastModified("/about-us"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/why-choose-us`,
      lastModified: getLastModified("/why-choose-us"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/india-tours-from-usa`,
      lastModified: getLastModified("/india-tours-from-usa"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/india-tours-from-uk`,
      lastModified: getLastModified("/india-tours-from-uk"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/india-tours-from-australia`,
      lastModified: getLastModified("/india-tours-from-australia"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/india-tours-from-canada`,
      lastModified: getLastModified("/india-tours-from-canada"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/india-tours-from-uae`,
      lastModified: getLastModified("/india-tours-from-uae"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/india-tours-from-germany`,
      lastModified: getLastModified("/india-tours-from-germany"),
      changeFrequency: "monthly",
      priority: 0.65,
    },
    {
      url: `${SITE_URL}/awards-recognition`,
      lastModified: getLastModified("/awards-recognition"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/testimonials`,
      lastModified: getLastModified("/testimonials"),
      changeFrequency: "weekly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/faq`,
      lastModified: getLastModified("/faq"),
      changeFrequency: "monthly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/privacy-policy`,
      lastModified: getLastModified("/privacy-policy"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${SITE_URL}/cancellation-policy-and-terms-and-conditions`,
      lastModified: getLastModified("/cancellation-policy-and-terms-and-conditions"),
      changeFrequency: "yearly",
      priority: 0.3,
    },
      {
      url: `${SITE_URL}/experiences/festival-tours`,
      lastModified: getLastModified("/experiences/festival-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/pilgrimage-tours`,
      lastModified: getLastModified("/experiences/pilgrimage-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/yoga-wellness-tours`,
      lastModified: getLastModified("/experiences/yoga-wellness-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/luxury-india-tours`,
      lastModified: getLastModified("/experiences/luxury-india-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/trekking-tours`,
      lastModified: getLastModified("/experiences/trekking-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/family-holidays`,
      lastModified: getLastModified("/experiences/family-holidays"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/varanasi-ganges-tours`,
      lastModified: getLastModified("/experiences/varanasi-ganges-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/rafting-tours`,
      lastModified: getLastModified("/experiences/rafting-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/photography-tours`,
      lastModified: getLastModified("/experiences/photography-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/buddhist-tours`,
      lastModified: getLastModified("/experiences/buddhist-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/food-cooking-tours`,
      lastModified: getLastModified("/experiences/food-cooking-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/village-experiences`,
      lastModified: getLastModified("/experiences/village-experiences"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/bird-watching`,
      lastModified: getLastModified("/experiences/bird-watching"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/honeymoon-tours`,
      lastModified: getLastModified("/experiences/honeymoon-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/udaipur-honeymoon`,
      lastModified: getLastModified("/experiences/udaipur-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/taj-mahal-honeymoon`,
      lastModified: getLastModified("/experiences/taj-mahal-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/rajasthan-palace-honeymoon`,
      lastModified: getLastModified("/experiences/rajasthan-palace-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/kerala-backwaters-honeymoon`,
      lastModified: getLastModified("/experiences/kerala-backwaters-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/kashmir-honeymoon`,
      lastModified: getLastModified("/experiences/kashmir-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/andaman-beach-honeymoon`,
      lastModified: getLastModified("/experiences/andaman-beach-honeymoon"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/experiences/desert-safari`,
      lastModified: getLastModified("/experiences/desert-safari"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/tiger-safari-tours`,
      lastModified: getLastModified("/experiences/tiger-safari-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/heritage-tours`,
      lastModified: getLastModified("/experiences/heritage-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/palace-fort-tours`,
      lastModified: getLastModified("/experiences/palace-fort-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/unesco-heritage-sites`,
      lastModified: getLastModified("/experiences/unesco-heritage-sites"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/cultural-tours`,
      lastModified: getLastModified("/experiences/cultural-tours"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/spiritual-india`,
      lastModified: getLastModified("/experiences/spiritual-india"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/experiences/lumbini`,
      lastModified: getLastModified("/experiences/lumbini"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/experiences/everest-region`,
      lastModified: getLastModified("/experiences/everest-region"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/experiences/kumbh-mela`,
      lastModified: getLastModified("/experiences/kumbh-mela"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/the-urs-festival-ajmer`,
      lastModified: getLastModified("/experiences/the-urs-festival-ajmer"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/elephant-festival`,
      lastModified: getLastModified("/experiences/elephant-festival"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/teej-festival`,
      lastModified: getLastModified("/experiences/teej-festival"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/camel-festival`,
      lastModified: getLastModified("/experiences/camel-festival"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/diwali`,
      lastModified: getLastModified("/experiences/diwali"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/goa-carnival`,
      lastModified: getLastModified("/experiences/goa-carnival"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/onam`,
      lastModified: getLastModified("/experiences/onam"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/international-yoga-festival-rishikesh`,
      lastModified: getLastModified("/experiences/international-yoga-festival-rishikesh"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/pushkar-fair`,
      lastModified: getLastModified("/experiences/pushkar-fair"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${SITE_URL}/experiences/kutch-mahotsav`,
      lastModified: getLastModified("/experiences/kutch-mahotsav"),
      changeFrequency: "yearly",
      priority: 0.6,
    },
      {
      url: `${SITE_URL}/tours`,
      lastModified: getLastModified("/tours"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/tours/3-5-day-tours`,
      lastModified: getLastModified("/tours/3-5-day-tours"),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/6-9-day-tours`,
      lastModified: getLastModified("/tours/6-9-day-tours"),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/10-14-day-tours`,
      lastModified: getLastModified("/tours/10-14-day-tours"),
      changeFrequency: "weekly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/15-plus-day-tours`,
      lastModified: getLastModified("/tours/15-plus-day-tours"),
      changeFrequency: "weekly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/tours/india-highlights`,
      lastModified: getLastModified("/tours/india-highlights"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/rajasthan-tours`,
      lastModified: getLastModified("/tours/rajasthan-tours"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/tours/rajasthan-tours-classic`,
      lastModified: getLastModified("/tours/rajasthan-tours-classic"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/rajasthan-highlights`,
      lastModified: getLastModified("/tours/rajasthan-highlights"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/jaipur-city-tour`,
      lastModified: getLastModified("/tours/jaipur-city-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/udaipur-tour`,
      lastModified: getLastModified("/tours/udaipur-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/jodhpur-tour`,
      lastModified: getLastModified("/tours/jodhpur-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/jaisalmer-tour`,
      lastModified: getLastModified("/tours/jaisalmer-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/pushkar-tour`,
      lastModified: getLastModified("/tours/pushkar-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/ranthambore-tour`,
      lastModified: getLastModified("/tours/ranthambore-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/taj-mahal-tours`,
      lastModified: getLastModified("/tours/taj-mahal-tours"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/kerala-tours`,
      lastModified: getLastModified("/tours/kerala-tours"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/kashmir-ladakh-tours`,
      lastModified: getLastModified("/tours/kashmir-ladakh-tours"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/wildlife-tiger-safari-tours`,
      lastModified: getLastModified("/tours/wildlife-tiger-safari-tours"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/hill-stations-tours`,
      lastModified: getLastModified("/tours/hill-stations-tours"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/goa-and-beaches-tours`,
      lastModified: getLastModified("/tours/goa-and-beaches-tours"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/nepal-and-bhutan-tours`,
      lastModified: getLastModified("/tours/nepal-and-bhutan-tours"),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/himachal-tour`,
      lastModified: getLastModified("/tours/himachal-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/south-india-tours`,
      lastModified: getLastModified("/tours/south-india-tours"),
      changeFrequency: "weekly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/south-india-tours-classic`,
      lastModified: getLastModified("/tours/south-india-tours-classic"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/chennai-tour`,
      lastModified: getLastModified("/tours/chennai-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/mahabalipuram-tour`,
      lastModified: getLastModified("/tours/mahabalipuram-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/madurai-tour`,
      lastModified: getLastModified("/tours/madurai-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/pondicherry-tour`,
      lastModified: getLastModified("/tours/pondicherry-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/tamil-nadu-beaches-tour`,
      lastModified: getLastModified("/tours/tamil-nadu-beaches-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/kashmir-ladakh-tours-classic`,
      lastModified: getLastModified("/tours/kashmir-ladakh-tours-classic"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/ladakh-tour`,
      lastModified: getLastModified("/tours/ladakh-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/kashmir-valley-tour`,
      lastModified: getLastModified("/tours/kashmir-valley-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/kerala-tours-classic`,
      lastModified: getLastModified("/tours/kerala-tours-classic"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/alleppey-backwaters-tour`,
      lastModified: getLastModified("/tours/alleppey-backwaters-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/munnar-tour`,
      lastModified: getLastModified("/tours/munnar-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/periyar-wildlife-tour`,
      lastModified: getLastModified("/tours/periyar-wildlife-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/kochi-tour`,
      lastModified: getLastModified("/tours/kochi-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/kerala-beaches-tour`,
      lastModified: getLastModified("/tours/kerala-beaches-tour"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/rajasthan-culture-heritage-trail`,
      lastModified: getLastModified("/tours/rajasthan-culture-heritage-trail"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/rajasthan-wildlife-safari`,
      lastModified: getLastModified("/tours/rajasthan-wildlife-safari"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/grand-rajasthan-circuit`,
      lastModified: getLastModified("/tours/grand-rajasthan-circuit"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/wildlife-tours`,
      lastModified: getLastModified("/tours/wildlife-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/kaziranga-tour`,
      lastModified: getLastModified("/tours/kaziranga-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/odisha-tour`,
      lastModified: getLastModified("/tours/odisha-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/mumbai-tour`,
      lastModified: getLastModified("/tours/mumbai-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/gujarat-beaches-tour`,
      lastModified: getLastModified("/tours/gujarat-beaches-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/maharashtra-tour`,
      lastModified: getLastModified("/tours/maharashtra-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/maharashtra-beaches-tour`,
      lastModified: getLastModified("/tours/maharashtra-beaches-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/north-india-tours`,
      lastModified: getLastModified("/tours/north-india-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/kolkata-tour`,
      lastModified: getLastModified("/tours/kolkata-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/darjeeling-tour`,
      lastModified: getLastModified("/tours/darjeeling-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/sikkim-tour`,
      lastModified: getLastModified("/tours/sikkim-tour"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/north-india-highlights`,
      lastModified: getLastModified("/tours/north-india-highlights"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/tours/nepal-tours`,
      lastModified: getLastModified("/tours/nepal-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/bhutan-tours`,
      lastModified: getLastModified("/tours/bhutan-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/nepal-bhutan-tours`,
      lastModified: getLastModified("/tours/nepal-bhutan-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/india-nepal-tours`,
      lastModified: getLastModified("/tours/india-nepal-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/india-bhutan-tours`,
      lastModified: getLastModified("/tours/india-bhutan-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/india-nepal-bhutan-tours`,
      lastModified: getLastModified("/tours/india-nepal-bhutan-tours"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour`,
      lastModified: getLastModified("/tours/golden-triangle-tour"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour-classic`,
      lastModified: getLastModified("/tours/golden-triangle-tour-classic"),
      changeFrequency: "monthly",
      priority: 0.85,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour-ranthambore`,
      lastModified: getLastModified("/tours/golden-triangle-tour-ranthambore"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour-udaipur`,
      lastModified: getLastModified("/tours/golden-triangle-tour-udaipur"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour-varanasi`,
      lastModified: getLastModified("/tours/golden-triangle-tour-varanasi"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/tours/golden-triangle-tour-ajmer-pushkar`,
      lastModified: getLastModified("/tours/golden-triangle-tour-ajmer-pushkar"),
      changeFrequency: "monthly",
      priority: 0.75,
    },
    {
      url: `${SITE_URL}/experiences`,
      lastModified: getLastModified("/experiences"),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/car-rental`,
      lastModified: getLastModified("/car-rental"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/car-rental/sedan`,
      lastModified: getLastModified("/car-rental/sedan"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/car-rental/suv`,
      lastModified: getLastModified("/car-rental/suv"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/car-rental/tempo-traveller`,
      lastModified: getLastModified("/car-rental/tempo-traveller"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/car-rental/luxury-cars`,
      lastModified: getLastModified("/car-rental/luxury-cars"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/car-rental/coaches`,
      lastModified: getLastModified("/car-rental/coaches"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india`,
      lastModified: getLastModified("/best-time-to-visit-india"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/january`,
      lastModified: getLastModified("/best-time-to-visit-india/january"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/february`,
      lastModified: getLastModified("/best-time-to-visit-india/february"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/march`,
      lastModified: getLastModified("/best-time-to-visit-india/march"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/april`,
      lastModified: getLastModified("/best-time-to-visit-india/april"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/may`,
      lastModified: getLastModified("/best-time-to-visit-india/may"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/june`,
      lastModified: getLastModified("/best-time-to-visit-india/june"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/july`,
      lastModified: getLastModified("/best-time-to-visit-india/july"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/august`,
      lastModified: getLastModified("/best-time-to-visit-india/august"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/september`,
      lastModified: getLastModified("/best-time-to-visit-india/september"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/october`,
      lastModified: getLastModified("/best-time-to-visit-india/october"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/november`,
      lastModified: getLastModified("/best-time-to-visit-india/november"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${SITE_URL}/best-time-to-visit-india/december`,
      lastModified: getLastModified("/best-time-to-visit-india/december"),
      changeFrequency: "yearly",
      priority: 0.7,
    },
  ];
}
