import type { CityCard } from "@/components/destinations/CityGrid";

/**
 * Duration-filtered listings for the four "By Duration" tour pages
 * (/tours/3-5-day-tours, /tours/6-9-day-tours, /tours/10-14-day-tours,
 * /tours/15-plus-day-tours). Built by grouping every real, live single-
 * itinerary tour page by its `Duration` quick fact.
 *
 * Deliberately excludes:
 * - The 4 thematic hub pages (golden-triangle-tour, kashmir-ladakh-tours,
 *   kerala-tours, south-india-tours) which aggregate several variants
 *   at different lengths rather than being one single itinerary.
 * - 6 orphaned/dead content files with no live route
 *   (golden-triangle-delhi-agra-jaipur-* x5, rajasthan-tours.ts) —
 *   confirmed unreferenced by any route before this file was built.
 *
 * No real itinerary currently runs 15+ days, so there is no
 * `fifteenPlusDayTours` export — that page renders an honest empty
 * state with a custom-itinerary CTA instead of a fabricated list.
 */

export const threeToFiveDayTours: CityCard[] = [
  {
    name: "Mahabalipuram Tour",
    tagline: "3 Days / 2 Nights",
    description: "UNESCO Rock-Cut Monuments",
    href: "/tours/mahabalipuram-tour",
    image: "/images/destinations/chennai.webp",
    imageAlt: "The Shore Temple, Mahabalipuram",
  },
  {
    name: "Taj Mahal Tours",
    tagline: "3 Days / 2 Nights",
    description: "Agra, Properly Explored",
    href: "/tours/taj-mahal-tours",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Alleppey Backwaters Tour",
    tagline: "4 Days / 3 Nights",
    description: "Houseboats & Palm-Lined Canals",
    href: "/tours/alleppey-backwaters-tour",
    image: "/images/destinations/alleppey-backwaters.webp",
    imageAlt: "A traditional houseboat on Alleppey's backwaters, Kerala",
  },
  {
    name: "Chennai City Tour",
    tagline: "4 Days / 3 Nights",
    description: "Temples, Beaches & the Gateway to the South",
    href: "/tours/chennai-tour",
    image: "/images/destinations/marina-beach-chennai.webp",
    imageAlt: "Sunset over Marina Beach, Chennai",
  },
  {
    name: "Darjeeling Tour",
    tagline: "4 Days / 3 Nights",
    description: "Tea Gardens & the Himalayan Railway",
    href: "/tours/darjeeling-tour",
    image: "/images/destinations/Darjeeling.webp",
    imageAlt: "Darjeeling town on the hillside, West Bengal",
  },
  {
    name: "Jaipur City Tour",
    tagline: "4 Days / 3 Nights",
    description: "The Pink City in Depth",
    href: "/tours/jaipur-city-tour",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "Jaisalmer Tour",
    tagline: "4 Days / 3 Nights",
    description: "The Golden City in Depth",
    href: "/tours/jaisalmer-tour",
    image: "/images/destinations/jaisalmer-fort.webp",
    imageAlt: "Jaisalmer Fort's golden sandstone walls at sunset",
  },
  {
    name: "Jodhpur Tour",
    tagline: "4 Days / 3 Nights",
    description: "The Blue City in Depth",
    href: "/tours/jodhpur-tour",
    image: "/images/destinations/mehrangarh-fort-jodhpur.webp",
    imageAlt: "Mehrangarh Fort towering above Jodhpur's blue-washed old town",
  },
  {
    name: "Kaziranga Tour",
    tagline: "4 Days / 3 Nights",
    description: "Rhino Safaris on the Brahmaputra Floodplain",
    href: "/tours/kaziranga-tour",
    image: "/images/destinations/kaziranga.webp",
    imageAlt: "A one-horned rhinoceros crossing a safari track, Kaziranga National Park",
  },
  {
    name: "Kerala Beaches Tour",
    tagline: "4 Days / 3 Nights",
    description: "Kovalam & Varkala",
    href: "/tours/kerala-beaches-tour",
    image: "/images/destinations/alleppey-2.webp",
    imageAlt: "Alleppey Beach at sunset, Kerala — a representative coastal image",
  },
  {
    name: "Kochi City Tour",
    tagline: "4 Days / 3 Nights",
    description: "Fort Kochi & Colonial Heritage",
    href: "/tours/kochi-tour",
    image: "/images/destinations/kochi-3.webp",
    imageAlt: "Chinese fishing nets at sunset, Fort Kochi, Kerala",
  },
  {
    name: "Kolkata Tour",
    tagline: "4 Days / 3 Nights",
    description: "Colonial Grandeur & the Hooghly River",
    href: "/tours/kolkata-tour",
    image: "/images/destinations/kolkata-victoria-memorial.webp",
    imageAlt: "The Victoria Memorial, Kolkata",
  },
  {
    name: "Madurai Temple Tour",
    tagline: "4 Days / 3 Nights",
    description: "The Meenakshi Amman Temple",
    href: "/tours/madurai-tour",
    image: "/images/destinations/madurai.webp",
    imageAlt: "Meenakshi Amman Temple's colourful gopuram, Madurai",
  },
  {
    name: "Maharashtra Beaches Tour",
    tagline: "4 Days / 3 Nights",
    description: "Alibaug's Forts & the Konkan Coast",
    href: "/tours/maharashtra-beaches-tour",
    image: "/images/destinations/alibaug-beach.webp",
    imageAlt: "A beach in Alibaug, Maharashtra",
  },
  {
    name: "Mumbai Tour",
    tagline: "4 Days / 3 Nights",
    description: "Colonial Landmarks & the Arabian Sea",
    href: "/tours/mumbai-tour",
    image: "/images/destinations/Mumbai.webp",
    imageAlt: "Chhatrapati Shivaji Maharaj Terminus, Mumbai",
  },
  {
    name: "Munnar Hill Station Tour",
    tagline: "4 Days / 3 Nights",
    description: "Tea Gardens & Cool Mountain Air",
    href: "/tours/munnar-tour",
    image: "/images/destinations/munnar-tea-plantation.webp",
    imageAlt: "Rolling tea plantations in the mist, Munnar, Kerala",
  },
  {
    name: "North India Highlights",
    tagline: "4 Days / 3 Nights",
    description: "Delhi & Agra",
    href: "/tours/north-india-highlights",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Periyar Wildlife Tour",
    tagline: "4 Days / 3 Nights",
    description: "Thekkady's Tiger Reserve",
    href: "/tours/periyar-wildlife-tour",
    image: "/images/destinations/thekkady.webp",
    imageAlt: "A traditional houseboat on a palm-lined waterway near Thekkady, Kerala",
  },
  {
    name: "Pondicherry Tour",
    tagline: "4 Days / 3 Nights",
    description: "The French Quarter",
    href: "/tours/pondicherry-tour",
    image: "/images/destinations/pondicherry-french-quarter.webp",
    imageAlt: "Colonial-era villas in Pondicherry's French Quarter",
  },
  {
    name: "Pushkar Tour",
    tagline: "4 Days / 3 Nights",
    description: "The Holy Lake Town, Paired with Ajmer",
    href: "/tours/pushkar-tour",
    image: "/images/destinations/pushkar-lake-ghats.webp",
    imageAlt: "Pushkar Lake and its ghats at dusk",
  },
  {
    name: "Ranthambore Tour",
    tagline: "4 Days / 3 Nights",
    description: "Tiger Country, Properly Explored",
    href: "/tours/ranthambore-tour",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "A wild tiger at Ranthambore National Park",
  },
  {
    name: "Udaipur Tour",
    tagline: "4 Days / 3 Nights",
    description: "The City of Lakes in Depth",
    href: "/tours/udaipur-tour",
    image: "/images/destinations/udaipur-lake-palace.webp",
    imageAlt: "The Lake Palace floating on Lake Pichola, Udaipur",
  },
  {
    name: "Kashmir Valley Tour",
    tagline: "5 Days / 4 Nights",
    description: "Dal Lake, Gulmarg & Pahalgam",
    href: "/tours/kashmir-valley-tour",
    image: "/images/destinations/Srinagar-3.webp",
    imageAlt: "Houseboats on Dal Lake with snow-capped mountains behind, Srinagar",
  },
  {
    name: "Maharashtra Tour",
    tagline: "5 Days / 4 Nights",
    description: "Ajanta, Ellora & Shirdi",
    href: "/tours/maharashtra-tour",
    image: "/images/destinations/maharashtra-ajanta-caves.webp",
    imageAlt: "The interior of a rock-cut cave temple at Ajanta, Maharashtra",
  },
  {
    name: "Odisha Tour",
    tagline: "5 Days / 4 Nights",
    description: "The Sun Temple & the Golden Triangle of the East",
    href: "/tours/odisha-tour",
    image: "/images/destinations/odisha-konark-sun-temple.webp",
    imageAlt: "The Konark Sun Temple, Odisha",
  },
  {
    name: "Rajasthan Highlights",
    tagline: "5 Days / 4 Nights",
    description: "Jaipur & Udaipur",
    href: "/tours/rajasthan-highlights",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "Sikkim Tour",
    tagline: "5 Days / 4 Nights",
    description: "A Former Himalayan Buddhist Kingdom",
    href: "/tours/sikkim-tour",
    image: "/images/destinations/sikkim-tsomgo-lake.webp",
    imageAlt: "Tsomgo Lake in the Sikkim Himalayas",
  },
  {
    name: "Tamil Nadu Beaches Tour",
    tagline: "5 Days / 4 Nights",
    description: "Rameswaram & Kanyakumari",
    href: "/tours/tamil-nadu-beaches-tour",
    image: "/images/destinations/kanyakumari-beach.webp",
    imageAlt: "The Vivekananda Rock Memorial and Thiruvalluvar Statue off Kanyakumari's coast",
  },
];

export const sixToNineDayTours: CityCard[] = [
  {
    name: "Golden Triangle Tour",
    tagline: "6 Days / 5 Nights",
    description: "The Classic Golden Triangle",
    href: "/tours/golden-triangle-tour-classic",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Himachal Tour",
    tagline: "6 Days / 5 Nights",
    description: "Shimla & Manali",
    href: "/tours/himachal-tour",
    image: "/images/destinations/shimla-town.webp",
    imageAlt: "Shimla town built into the Himalayan hillside",
  },
  {
    name: "Kerala Tours",
    tagline: "6 Days / 5 Nights",
    description: "The Classic Circuit",
    href: "/tours/kerala-tours-classic",
    image: "/images/destinations/alleppey-backwaters.webp",
    imageAlt: "A traditional houseboat on Alleppey's backwaters, Kerala",
  },
  {
    name: "Ladakh Tour",
    tagline: "6 Days / 5 Nights",
    description: "Leh, Monasteries & Pangong Lake",
    href: "/tours/ladakh-tour",
    image: "/images/destinations/Leh-4.webp",
    imageAlt: "Pangong Lake with motorcycles parked on the shore, Ladakh",
  },
  {
    name: "South India Tours",
    tagline: "6 Days / 5 Nights",
    description: "The Classic Circuit",
    href: "/tours/south-india-tours-classic",
    image: "/images/destinations/chennai.webp",
    imageAlt: "The Shore Temple, Mahabalipuram, near Chennai",
  },
  {
    name: "Wildlife Tours",
    tagline: "6 Days / 5 Nights",
    description: "Tiger Safaris",
    href: "/tours/wildlife-tours",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "Wild tiger at Ranthambore National Park",
  },
  {
    name: "India Highlights",
    tagline: "7 Days / 6 Nights",
    description: "The Taj Mahal & Kerala's Backwaters",
    href: "/tours/india-highlights",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Bhutan Tours",
    tagline: "8 Days / 7 Nights",
    description: "Dzongs, Valleys & the Tiger's Nest",
    href: "/tours/bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "Golden Triangle Tour with Ajmer & Pushkar",
    tagline: "8 Days / 7 Nights",
    description: "The Golden Triangle, Extended to the Sacred Lake",
    href: "/tours/golden-triangle-tour-ajmer-pushkar",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "Golden Triangle Tour with Ranthambore",
    tagline: "8 Days / 7 Nights",
    description: "The Golden Triangle, With a Tiger Safari",
    href: "/tours/golden-triangle-tour-ranthambore",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "A wild tiger at Ranthambore National Park",
  },
  {
    name: "Nepal Tours",
    tagline: "8 Days / 7 Nights",
    description: "Temples, Mountains & the Jungle",
    href: "/tours/nepal-tours",
    image: "/images/destinations/pokhara-valley-machapuchare-view.webp",
    imageAlt: "Pokhara valley with Machapuchare mountain view, Nepal",
  },
  {
    name: "Rajasthan Culture & Heritage Trail",
    tagline: "8 Days / 7 Nights",
    description: "Forts, Havelis & Living Craft Traditions",
    href: "/tours/rajasthan-culture-heritage-trail",
    image: "/images/destinations/jaisalmer-patwon-ki-haveli.webp",
    imageAlt: "Ornately carved facade of Patwon Ki Haveli, Jaisalmer",
  },
  {
    name: "Rajasthan Tours",
    tagline: "8 Days / 7 Nights",
    description: "Land of Kings",
    href: "/tours/rajasthan-tours-classic",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "Rajasthan Wildlife Safari",
    tagline: "8 Days / 7 Nights",
    description: "Forts, Tigers & a Lake City",
    href: "/tours/rajasthan-wildlife-safari",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "A wild tiger at Ranthambore National Park",
  },
  {
    name: "Golden Triangle Tour with Udaipur",
    tagline: "9 Days / 8 Nights",
    description: "The Golden Triangle, Extended",
    href: "/tours/golden-triangle-tour-udaipur",
    image: "/images/destinations/udaipur-lake-palace.webp",
    imageAlt: "The Lake Palace floating on Lake Pichola, Udaipur",
  },
  {
    name: "Golden Triangle Tour with Varanasi",
    tagline: "9 Days / 8 Nights",
    description: "The Golden Triangle, Extended to the Ganges",
    href: "/tours/golden-triangle-tour-varanasi",
    image: "/images/destinations/varanasi-evening-ganges-aarti.webp",
    imageAlt: "Evening Ganga Aarti ceremony in Varanasi",
  },
  {
    name: "Kashmir & Ladakh Tour",
    tagline: "9 Days / 8 Nights",
    description: "The Complete Circuit",
    href: "/tours/kashmir-ladakh-tours-classic",
    image: "/images/destinations/Leh-4.webp",
    imageAlt: "Pangong Lake with motorcycles parked on the shore, Ladakh",
  },
  {
    name: "North India Tours",
    tagline: "9 Days / 8 Nights",
    description: "Delhi & Beyond",
    href: "/tours/north-india-tours",
    image: "/images/destinations/delhi-india-gate.webp",
    imageAlt: "India Gate at dusk, Delhi",
  },
];

export const tenToFourteenDayTours: CityCard[] = [
  {
    name: "India & Bhutan Tours",
    tagline: "11 Days / 10 Nights",
    description: "The Golden Triangle & the Tiger's Nest",
    href: "/tours/india-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "India & Nepal Tours",
    tagline: "11 Days / 10 Nights",
    description: "The Golden Triangle & the Himalayas",
    href: "/tours/india-nepal-tours",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Grand Rajasthan Circuit",
    tagline: "12 Days / 11 Nights",
    description: "The Full State, Six Cities",
    href: "/tours/grand-rajasthan-circuit",
    image: "/images/destinations/jaisalmer-desert.webp",
    imageAlt: "Camel caravan crossing the Thar Desert dunes near Jaisalmer",
  },
  {
    name: "India, Nepal & Bhutan Tours",
    tagline: "12 Days / 11 Nights",
    description: "Three Countries, One Himalayan Journey",
    href: "/tours/india-nepal-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "Nepal & Bhutan Tours",
    tagline: "12 Days / 11 Nights",
    description: "Two Himalayan Kingdoms in One Trip",
    href: "/tours/nepal-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
];
