import type { CityCard } from "@/components/destinations/CityGrid";

export const festivalCards: CityCard[] = [
  {
    name: "Pushkar Fair",
    tagline: "October / November",
    description: "One of the world's largest camel fairs, alongside a major pilgrimage at Pushkar's sacred lake.",
    href: "/themes/festival-tours/pushkar-fair",
    image: "/images/packages/jaipur-bikaner-jaisalmer-jodhpur-udaipur-pushkar.webp",
    imageAlt: "Traditional Rajasthani performers at the Pushkar Camel Fair",
  },
  {
    name: "Kumbh Mela",
    tagline: "Rotating, 12-year cycle",
    description: "The largest peaceful religious gathering on Earth, rotating between four sacred river sites.",
    href: "/themes/festival-tours/kumbh-mela",
    image: "/images/destinations/haridwar.webp",
    imageAlt: "Haridwar on the Ganges, one of the four Kumbh Mela host cities",
  },
  {
    name: "International Yoga Festival, Rishikesh",
    tagline: "Early March",
    description: "A week of yoga, meditation and Ayurveda in the town known as the Yoga Capital of the World.",
    href: "/themes/festival-tours/international-yoga-festival-rishikesh",
    image: "/images/destinations/rishikesh-2.webp",
    imageAlt: "Rishikesh, the Yoga Capital of the World, on the Ganges",
  },
  {
    name: "Camel Festival, Bikaner",
    tagline: "January",
    description: "Decorated camel processions, races and desert folk performances in Bikaner.",
    href: "/themes/festival-tours/camel-festival",
    image: "/images/packages/jaipur-bikaner-jaisalmer-jodhpur-udaipur-pushkar.webp",
    imageAlt: "Traditional Rajasthani performers at a desert camel festival",
  },
  {
    name: "Elephant Festival, Jaipur",
    tagline: "Around Holi (March)",
    description: "Elaborately painted elephants paraded through Jaipur, timed alongside the colour festival.",
    href: "/themes/festival-tours/elephant-festival",
    image: "/images/destinations/elephant-festival.webp",
    imageAlt: "Decorated elephants at the Elephant Festival, Jaipur",
  },
  {
    name: "Teej Festival",
    tagline: "July / August",
    description: "A royal Jaipur procession marking the monsoon, with women in traditional dress and flower-decorated swings.",
    href: "/themes/festival-tours/teej-festival",
    image: "/images/destinations/teej-festival.webp",
    imageAlt: "Women celebrating Teej Festival in traditional red attire",
  },
  {
    name: "Diwali",
    tagline: "October / November",
    description: "India's biggest festival — the Festival of Lights, at its most vivid in Varanasi and Amritsar.",
    href: "/themes/festival-tours/diwali",
    image: "/images/destinations/diwali.webp",
    imageAlt: "Diyas and rangoli lit for Diwali",
  },
  {
    name: "Goa Carnival",
    tagline: "February / March",
    description: "A Portuguese-heritage street carnival with parades, floats and live music across Goa.",
    href: "/themes/festival-tours/goa-carnival",
    image: "/images/destinations/goa-carnival.webp",
    imageAlt: "Colourful parade float at Goa Carnival",
  },
  {
    name: "Onam",
    tagline: "August / September",
    description: "Kerala's biggest festival — flower carpets, snake boat races, and a traditional feast.",
    href: "/themes/festival-tours/onam",
    image: "/images/destinations/onam.webp",
    imageAlt: "Traditional flower rangoli for Onam celebrations",
  },
  {
    name: "Kutch Mahotsav",
    tagline: "November – February",
    description: "A months-long desert festival on the white salt flats of the Rann of Kutch.",
    href: "/themes/festival-tours/kutch-mahotsav",
    image: "/images/destinations/kutch-mahotsav.webp",
    imageAlt: "Tented camp at Kutch Mahotsav, Rann of Kutch",
  },
] as const;
