import type { CityCard } from "@/components/destinations/CityGrid";
import type { MoreDestination } from "@/components/destinations/MoreDestinationsList";

export const featuredPackages: CityCard[] = [
  {
    name: "India Highlights",
    tagline: "The Taj Mahal & Kerala's Backwaters",
    description: "A 7-day flagship circuit pairing North India's icon with the tropical South for genuine range.",
    href: "/tours/india-highlights",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Golden Triangle Tour",
    tagline: "Delhi – Agra – Jaipur",
    description: "The classic first-time India route, covering the Taj Mahal and Rajasthan's capital.",
    href: "/tours/golden-triangle-tour",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Rajasthan Tours",
    tagline: "Land of Kings",
    description: "Forts, palaces and desert citadels across Jaipur, Udaipur, Jodhpur and beyond.",
    href: "/tours/rajasthan-tours",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "Rajasthan Highlights",
    tagline: "Jaipur & Udaipur in 5 Days",
    description: "A condensed Rajasthan trip for travellers with limited time, covering just the two most requested cities.",
    href: "/tours/rajasthan-highlights",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "North India Tours",
    tagline: "Delhi & Beyond",
    description: "Mughal monuments, colonial avenues, and the natural start of most India itineraries.",
    href: "/tours/north-india-tours",
    image: "/images/destinations/delhi-india-gate.webp",
    imageAlt: "India Gate at dusk, Delhi",
  },
  {
    name: "Kolkata Tour",
    tagline: "Colonial Grandeur & the Hooghly River",
    description: "The Victoria Memorial, India's last working tram network, and the potters' quarter of Kumartuli.",
    href: "/tours/kolkata-tour",
    image: "/images/destinations/kolkata-victoria-memorial.webp",
    imageAlt: "The Victoria Memorial, Kolkata",
  },
  {
    name: "Darjeeling Tour",
    tagline: "Tea Gardens & the Himalayan Railway",
    description: "Sunrise at Tiger Hill, a UNESCO steam railway, and a working tea garden.",
    href: "/tours/darjeeling-tour",
    image: "/images/destinations/Darjeeling.webp",
    imageAlt: "Darjeeling town on the hillside, West Bengal",
  },
  {
    name: "Sikkim Tour",
    tagline: "A Former Himalayan Buddhist Kingdom",
    description: "Gangtok's monasteries, a high-altitude glacial lake, and South Sikkim's giant hilltop statues.",
    href: "/tours/sikkim-tour",
    image: "/images/destinations/sikkim-tsomgo-lake.webp",
    imageAlt: "Tsomgo Lake in the Sikkim Himalayas",
  },
  {
    name: "North India Highlights",
    tagline: "Delhi & Agra in 4 Days",
    description: "A condensed trip for very limited time, covering just Delhi and the Taj Mahal.",
    href: "/tours/north-india-highlights",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Wildlife Tours",
    tagline: "Tiger Safaris",
    description: "Ranthambore and Sariska's tiger reserves, paired with Jaipur's forts.",
    href: "/tours/wildlife-tours",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "Wild tiger at Ranthambore National Park",
  },
  {
    name: "Kaziranga Tour",
    tagline: "Rhino Safaris on the Brahmaputra",
    description: "Home to roughly two-thirds of the world's remaining wild one-horned rhinoceroses.",
    href: "/tours/kaziranga-tour",
    image: "/images/destinations/kaziranga.webp",
    imageAlt: "A one-horned rhinoceros crossing a safari track, Kaziranga National Park",
  },
  {
    name: "Odisha Tour",
    tagline: "The Sun Temple & the Golden Triangle of the East",
    description: "Bhubaneswar's ancient temples, the Konark Sun Temple, and Chilika Lake's Irrawaddy dolphins.",
    href: "/tours/odisha-tour",
    image: "/images/destinations/odisha-konark-sun-temple.webp",
    imageAlt: "The Konark Sun Temple, Odisha",
  },
  {
    name: "Mumbai Tour",
    tagline: "Colonial Landmarks & the Arabian Sea",
    description: "The Gateway of India, a UNESCO railway terminus, and the rock-cut Elephanta Caves.",
    href: "/tours/mumbai-tour",
    image: "/images/destinations/Mumbai.webp",
    imageAlt: "Chhatrapati Shivaji Maharaj Terminus, Mumbai",
  },
  {
    name: "Gujarat Beaches Tour",
    tagline: "Diu's Colonial Coast & Somnath's Sacred Shore",
    description: "A Portuguese colonial island and one of Hinduism's most significant shore temples.",
    href: "/tours/gujarat-beaches-tour",
    image: "/images/destinations/gujarat-beaches.webp",
    imageAlt: "A quiet stretch of Gujarat's coastline",
  },
  {
    name: "Maharashtra Tour",
    tagline: "Ajanta, Ellora & Shirdi",
    description: "UNESCO rock-cut cave temples and one of India's most-visited pilgrimage towns, beyond Mumbai.",
    href: "/tours/maharashtra-tour",
    image: "/images/destinations/maharashtra-ajanta-caves.webp",
    imageAlt: "The interior of a rock-cut cave temple at Ajanta, Maharashtra",
  },
  {
    name: "Maharashtra Beaches Tour",
    tagline: "Alibaug's Forts & the Konkan Coast",
    description: "A fort-dotted coastline near Mumbai, and a quieter beach town further south at Ganpatipule.",
    href: "/tours/maharashtra-beaches-tour",
    image: "/images/destinations/alibaug-beach.webp",
    imageAlt: "A beach in Alibaug, Maharashtra",
  },
  {
    name: "Nepal Tours",
    tagline: "Temples, Mountains & the Jungle",
    description: "Kathmandu's temples, Himalayan sunrise views, and a Chitwan jungle safari.",
    href: "/tours/nepal-tours",
    image: "/images/destinations/pokhara-valley-machapuchare-view.webp",
    imageAlt: "Pokhara valley with Machapuchare mountain view, Nepal",
  },
  {
    name: "Bhutan Tours",
    tagline: "Dzongs, Valleys & the Tiger's Nest",
    description: "Thimphu, Punakha, Gangtey and the cliffside hike to Paro Taktsang.",
    href: "/tours/bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "Nepal & Bhutan Tours",
    tagline: "Two Himalayan Kingdoms in One Trip",
    description: "Kathmandu and Pokhara, then Bhutan's dzongs and the Tiger's Nest, in one 12-day circuit.",
    href: "/tours/nepal-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "India & Nepal Tours",
    tagline: "The Golden Triangle & the Himalayas",
    description: "Delhi, Agra and Jaipur, then Kathmandu, Nagarkot and Pokhara, in one 11-day circuit.",
    href: "/tours/india-nepal-tours",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "India & Bhutan Tours",
    tagline: "The Golden Triangle & the Tiger's Nest",
    description: "Delhi, Agra and Jaipur, then Thimphu, Punakha and the Tiger's Nest, on a direct Delhi–Paro flight.",
    href: "/tours/india-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "India, Nepal & Bhutan Tours",
    tagline: "Three Countries, One Himalayan Journey",
    description: "The Taj Mahal, Kathmandu's temples and Bhutan's Tiger's Nest, in one 12-day circuit.",
    href: "/tours/india-nepal-bhutan-tours",
    image: "/images/destinations/paro-taktsang-tigers-nest.webp",
    imageAlt: "Paro Taktsang, the Tiger's Nest Monastery, Bhutan",
  },
  {
    name: "Taj Mahal Tours",
    tagline: "Sunrise at the Taj",
    description: "Agra alone, properly explored — the Taj Mahal, Agra Fort and Fatehpur Sikri.",
    href: "/tours/taj-mahal-tours",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Kerala Tours",
    tagline: "God's Own Country",
    description: "Backwaters, tea gardens, wildlife and colonial heritage, in six different shapes.",
    href: "/tours/kerala-tours",
    image: "/images/destinations/alleppey-backwaters.webp",
    imageAlt: "A traditional houseboat on Alleppey's backwaters, Kerala",
  },
  {
    name: "Kashmir & Ladakh Tours",
    tagline: "Paradise on Earth",
    description: "Dal Lake's houseboats and Ladakh's high-altitude monasteries, in three different shapes.",
    href: "/tours/kashmir-ladakh-tours",
    image: "/images/destinations/Leh-4.webp",
    imageAlt: "Pangong Lake with motorcycles parked on the shore, Ladakh",
  },
  {
    name: "Himachal Tour",
    tagline: "Shimla & Manali",
    description: "Colonial hill-station architecture and a forested valley gateway to the high Himalayas.",
    href: "/tours/himachal-tour",
    image: "/images/destinations/shimla-town.webp",
    imageAlt: "Shimla town built into the Himalayan hillside",
  },
  {
    name: "South India Tours",
    tagline: "Temples, Coast & French Heritage",
    description: "Dravidian temple architecture, rock-cut monuments and colonial heritage, in six different shapes.",
    href: "/tours/south-india-tours",
    image: "/images/destinations/chennai.webp",
    imageAlt: "The Shore Temple, Mahabalipuram, near Chennai",
  },
] as const;

const homepagePackageOrder = [
  "Golden Triangle Tour",
  "Rajasthan Tours",
  "Kerala Tours",
  "Taj Mahal Tours",
  "Kashmir & Ladakh Tours",
  "South India Tours",
  "Wildlife Tours",
  "Nepal Tours",
];

export const homepagePackages: CityCard[] = homepagePackageOrder
  .map((name) => featuredPackages.find((card) => card.name === name))
  .filter((card): card is CityCard => card !== undefined);

export const morePackages: MoreDestination[] = [
  { name: "3–5 Days", href: "/tours/3-5-day-tours" },
  { name: "6–9 Days", href: "/tours/6-9-day-tours" },
  { name: "10–14 Days", href: "/tours/10-14-day-tours" },
  { name: "15+ Days", href: "/tours/15-plus-day-tours" },
] as const;
