import type { CityCard } from "@/components/destinations/CityGrid";
import type { MoreDestination } from "@/components/destinations/MoreDestinationsList";

export const featuredPackages: CityCard[] = [
  {
    name: "Golden Triangle Tour",
    tagline: "Delhi – Agra – Jaipur",
    description: "The classic first-time India route, covering the Taj Mahal and Rajasthan's capital.",
    href: "/tours/golden-triangle-tour",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Rajasthan Tours",
    tagline: "Land of Kings",
    description: "Forts, palaces and desert citadels across Jaipur, Udaipur, Jodhpur and beyond.",
    href: "/tours/rajasthan-tours",
    image: "/images/destinations/amber-fort-jaipur.webp",
    imageAlt: "Amber Fort at sunset, Jaipur, Rajasthan",
  },
  {
    name: "North India Tours",
    tagline: "Delhi & Beyond",
    description: "Mughal monuments, colonial avenues, and the natural start of most India itineraries.",
    href: "/tours/north-india-tours",
    image: "/images/destinations/delhi-india-gate.webp",
    imageAlt: "India Gate at dusk, Delhi",
  },
  {
    name: "Wildlife Tours",
    tagline: "Tiger Safaris",
    description: "Ranthambore, Sariska, Bandhavgarh and Kaziranga's one-horned rhinos.",
    href: "/tours/wildlife-tours",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "Wild tiger at Ranthambore National Park",
  },
  {
    name: "Nepal Tours",
    tagline: "Temples, Mountains & the Jungle",
    description: "Kathmandu's temples, Himalayan sunrise views, and a Chitwan jungle safari.",
    href: "/tours/nepal-tours",
    image: "/images/destinations/pokhara-valley-machapuchare-view.webp",
    imageAlt: "Pokhara valley with Machapuchare mountain view, Nepal",
  },
  {
    name: "Taj Mahal Tours",
    tagline: "Sunrise at the Taj",
    description: "Agra alone, properly explored — the Taj Mahal, Agra Fort and Fatehpur Sikri.",
    href: "/tours/taj-mahal-tours",
    image: "/images/destinations/agra-taj-mahal.webp",
    imageAlt: "Taj Mahal at sunrise, Agra",
  },
  {
    name: "Kerala Tours",
    tagline: "God's Own Country",
    description: "Backwaters, tea gardens, wildlife and colonial heritage, in six different shapes.",
    href: "/tours/kerala-tours",
    image: "/images/destinations/alleppey-backwaters.webp",
    imageAlt: "A traditional houseboat on Alleppey's backwaters, Kerala",
  },
  {
    name: "Kashmir & Ladakh Tours",
    tagline: "Paradise on Earth",
    description: "Dal Lake's houseboats and Ladakh's high-altitude monasteries, in three different shapes.",
    href: "/tours/kashmir-ladakh-tours",
    image: "/images/destinations/Leh-4.webp",
    imageAlt: "Pangong Lake with motorcycles parked on the shore, Ladakh",
  },
  {
    name: "South India Tours",
    tagline: "Temples, Coast & French Heritage",
    description: "Dravidian temple architecture, rock-cut monuments and colonial heritage, in six different shapes.",
    href: "/tours/south-india-tours",
    image: "/images/destinations/chennai.webp",
    imageAlt: "The Shore Temple, Mahabalipuram, near Chennai",
  },
] as const;

export const morePackages: MoreDestination[] = [
  { name: "Bhutan Tours", href: "/tours/bhutan-tours" },
  { name: "India & Nepal Tours", href: "/tours/india-nepal-tours" },
  { name: "India, Nepal & Bhutan", href: "/tours/india-nepal-bhutan-tours" },
  { name: "Nepal & Bhutan Tours", href: "/tours/nepal-bhutan-tours" },
  { name: "Rajasthan Highlights", href: "/tours/rajasthan-highlights" },
  { name: "North India Highlights", href: "/tours/north-india-highlights" },
  { name: "India Highlights", href: "/tours/india-highlights" },
  { name: "3–5 Days", href: "/tours/3-5-day-tours" },
  { name: "6–9 Days", href: "/tours/6-9-day-tours" },
  { name: "10–14 Days", href: "/tours/10-14-day-tours" },
  { name: "15+ Days", href: "/tours/15-plus-day-tours" },
] as const;
