import type { CityCard } from "@/components/destinations/CityGrid";
import type { MoreDestination } from "@/components/destinations/MoreDestinationsList";

export const featuredThemes: CityCard[] = [
  {
    name: "Festival Tours",
    tagline: "Time It Right",
    description: "The Pushkar Camel Fair, Kumbh Mela, Diwali and more — plan your trip around a real celebration.",
    href: "/experiences/festival-tours",
    image: "/images/packages/jaipur-bikaner-jaisalmer-jodhpur-udaipur-pushkar.webp",
    imageAlt: "Traditional Rajasthani performers at the Pushkar Camel Fair",
  },
  {
    name: "Heritage Tours",
    tagline: "Forts & Palaces",
    description: "The palace hotels and fortified cities that define Rajasthan and North India.",
    href: "/experiences/heritage-tours",
    image: "/images/destinations/mehrangarh-fort-jodhpur.webp",
    imageAlt: "Mehrangarh Fort overlooking the blue city of Jodhpur",
  },
  {
    name: "Tiger Safari Tours",
    tagline: "Wildlife & Nature",
    description: "Ranthambore, Sariska, Bandhavgarh and Kaziranga's tiger and rhino safaris.",
    href: "/experiences/tiger-safari-tours",
    image: "/images/destinations/ranthambore-tiger.webp",
    imageAlt: "Wild tiger at Ranthambore National Park",
  },
  {
    name: "Spiritual India",
    tagline: "Ganges & Beyond",
    description: "The evening Ganga Aarti in Varanasi, and India's most significant pilgrimage sites.",
    href: "/experiences/spiritual-india",
    image: "/images/destinations/varanasi-evening-ganges-aarti.webp",
    imageAlt: "Evening Ganga Aarti ceremony in Varanasi",
  },
  {
    name: "Desert Safari",
    tagline: "The Thar Desert",
    description: "Camel safaris and overnight camping in the dunes outside Jaisalmer.",
    href: "/experiences/desert-safari",
    image: "/images/destinations/jaisalmer-desert.webp",
    imageAlt: "Camel caravan crossing the Thar Desert dunes near Jaisalmer",
  },
  {
    name: "Honeymoon Tours",
    tagline: "Luxury & Romance",
    description: "Palace hotels and the Lake Palace in Udaipur, built around privacy and romance.",
    href: "/experiences/honeymoon-tours",
    image: "/images/destinations/udaipur-lake-palace.webp",
    imageAlt: "Lake Palace floating on Lake Pichola, Udaipur",
  },
] as const;

export const moreThemes: MoreDestination[] = [
  { name: "Palace & Fort Tours", href: "/experiences/palace-fort-tours" },
  { name: "UNESCO Heritage Sites", href: "/experiences/unesco-heritage-sites" },
  { name: "Cultural Tours", href: "/experiences/cultural-tours" },
  { name: "Village Experiences", href: "/experiences/village-experiences" },
  { name: "Bird Watching", href: "/experiences/bird-watching" },
  { name: "Nature & Landscape", href: "/experiences/nature-landscape" },
  { name: "National Parks", href: "/experiences/national-parks" },
  { name: "Varanasi & Ganges", href: "/experiences/varanasi-ganges" },
  { name: "Buddhist Tours", href: "/experiences/buddhist-tours" },
  { name: "Yoga & Wellness", href: "/experiences/yoga-wellness" },
  { name: "Temple Tours", href: "/experiences/temple-tours" },
  { name: "Luxury India", href: "/experiences/luxury-india" },
  { name: "Luxury Rajasthan", href: "/experiences/luxury-rajasthan" },
  { name: "Romantic Getaways", href: "/experiences/romantic-getaways" },
  { name: "Palace Experiences", href: "/experiences/palace-experiences" },
  { name: "Himalayan Adventures", href: "/experiences/himalayan-adventures" },
  { name: "Trekking", href: "/experiences/trekking" },
  { name: "Rafting", href: "/experiences/rafting" },
  { name: "Adventure Tours", href: "/experiences/adventure-tours" },
  { name: "Food & Cooking", href: "/experiences/food-cooking" },
  { name: "Photography Tours", href: "/experiences/photography-tours" },
  { name: "Family Holidays", href: "/experiences/family-holidays" },
  { name: "Solo Travel", href: "/experiences/solo-travel" },
] as const;
